[package]
name = "acvm"
version = "0.2.0"
authors = ["Kevaundray Wedderburn <kevtheappdev@gmail.com>"]
edition = "2021"
license = "MIT"
description = "The virtual machine that processes ACIR given a backend/proof system."
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = "0.4"
num-traits = "0.2"
acir = { version = "0.1.0", path = "../acir" }

sled = "0.34.6"
acir_field = { version = "0.1.0", path = "../acir_field", default-features = false }
sha2 = "0.9.3"
blake2 = "0.9.1"
hex = "0.4.2"
k256 = { version = "0.7.2", features = [
    "ecdsa",
    "ecdsa-core",
    "sha256",
    "digest",
    "arithmetic",
] }
indexmap = "1.7.0"

[features]
bn254 = ["acir_field/bn254"]
bls12_381 = ["acir_field/bls12_381"]

[dev-dependencies]
tempfile = "3.2.0"
