[package]
name = "acir"
version = "0.2.1"
authors = ["Kevaundray Wedderburn <kevtheappdev@gmail.com>"]
edition = "2021"
license = "MIT"
description = "ACIR is the IR that the VM processes, it is analogous to LLVM IR"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
acir_field = { version = "0.2.1", path = "../acir_field" }
serde = { version = "1.0.136", features = ["derive"] }
rmp-serde = "1.1.0"
flate2 = "1.0.24"

[dev-dependencies]
serde_json = "1.0"
